"""Map and INI patching helpers for the Mental Omega randomizer launcher."""
import re
import shutil
from datetime import datetime

from randomizer_paths import BACKUP_DIR
from randomizer_rewards import (
    ALWAYS_AVAILABLE_TECH_IDS,
    BUFF_TARGETS,
    CLONE_REQUIRED_BUFF_TYPES,
    HOUSE_SCOPED_BUFF_TYPES,
    REWARD_POOL,
    UNIT_STAT_BUFF_TYPES,
    WEAPON_STAT_BUFF_TYPES,
    canonical_reward,
    canonical_rewards,
    check_rewards,
    house_category_suffix,
)

HOOKED_MAP_MARKER = '; Generated by Mental Omega Randomizer Launcher objective hook'
COMMON_BUILD_TAB_TECH_LOCKS = {
    # These appear in INI/Map Code/No Bases.ini as broadly start/build-enabled
    # infantry or units. Most are not randomizer rewards yet, so keep them out
    # of player build tabs until we intentionally add them to the item pool.
    'ABRM', 'AHVYBOT2', 'AMC', 'ARCH', 'ARMA', 'BANE', 'BANE_N', 'BASS',
    'BFRT', 'BGGY', 'BLZZ', 'BOREK', 'BRUTE', 'BURA', 'CHRP', 'CHRTNK',
    'CNTR', 'COON', 'COVE', 'CTNK', 'DESOR', 'DEVI', 'DEVO', 'DRON',
    'DTRUCK', 'DUNE', 'EMPR', 'ENFO', 'ENTK', 'FLAMER', 'GHOST', 'GHTNK',
    'HARP', 'HCAN', 'HOWI', 'HUNTR', 'IDRAG', 'IVAN', 'JTNK', 'KINGS',
    'KTNK', 'MARA', 'MEGA', 'MGTK', 'MOTOR', 'MTNK', 'PHNT', 'PLAG',
    'PROME', 'QTNK', 'QUICK', 'RACC', 'RAIL', 'RAMW', 'RAVA', 'RIOT',
    'ROACH', 'ROBO', 'ROADR', 'SCAV', 'SDRN', 'SEITAAD', 'SHADOW',
    'SHRAY', 'SNIPE', 'SREF', 'STALKER', 'STING', 'STNK', 'SUPR',
    'TELE', 'TENGU', 'TNKKIL', 'TRACTOR', 'TRIKE', 'V3', 'VCARR',
    'YDOG', 'YURI', 'ZORB',
}
EXTRA_TECH_LOCKS = {
    # Common naval and mission-provided tech that can appear before the
    # randomizer has granted it. Keep this broader than the reward pool.
    'AEGIS', 'AKULA', 'CARRIER', 'DBOAT', 'DEST', 'DLPH', 'DRED', 'HCRUIS',
    'LCRF', 'SAPC', 'SQD', 'SUB', 'SUB2',
    # Extra Mental Omega tech seen in campaign spawn maps.
    'AERO', 'AICLEG', 'AITHOR', 'AMCV', 'BEAG', 'BLIGHT', 'CHRTNK', 'CRYO',
    'CRYOAI', 'DUST', 'FOX', 'GAGAP', 'GASTAS', 'GAWEAT', 'HBIRD', 'LIONH',
    'MWF', 'NAHAMM', 'NAINDP', 'NAIRDM', 'NAMISL', 'NASCOM', 'ORCA', 'RAVA',
    'REAP', 'ROBOW', 'SBTR', 'SEIZER', 'SHOCK', 'SIEG', 'SMCV', 'SPY', 'SREF',
    'STORM', 'THOR', 'VENOM', 'VOLKOV',
    # Soviet campaign combat tech that can appear in build tabs even when it
    # is not part of the current randomizer access pool.
    'APOC', 'DESO', 'HOWI', 'HTK', 'MAMM', 'V3', 'WOLF', 'ZEP',
    # Common Allied infantry/support units exposed by early campaign barracks.
    'E1', 'GGI', 'ADOG', 'AMEDIC', 'JUMPJET', 'ENFO', 'GHOST', 'SUPR', 'SNIPE',
} | COMMON_BUILD_TAB_TECH_LOCKS
SCRIPTED_TECH_LOCK_EXCLUSIONS = {
    # These can appear as campaign-critical scripted/pre-placed units. Hard
    # TechLevel locks can stop trigger-created teams from spawning, causing
    # immediate fail/win chains on missions such as Bad Apple.
    'ENFO', 'GHOST', 'SNIPE', 'SPY', 'SUPR', 'TANY', 'TANYA', 'VOLKOV',
    # Extra campaign combat tech that is not a randomizer access reward yet.
    # BuildLimit blocks player production while keeping scripted teams safer
    # than a hard TechLevel lock.
    'APOC', 'DESO', 'MAMM', 'WOLF', 'ZEP',
} | COMMON_BUILD_TAB_TECH_LOCKS
SCRIPTED_TECH_BUILD_LIMIT = '0'

RANDOMIZER_RULES_MARKER = '; Generated by Mental Omega Randomizer Launcher'
LOCKED_TECH_LEVEL = '11'
UNLOCKED_TECH_LEVEL = '1'


def now_stamp():
    return datetime.now().strftime('%Y%m%d-%H%M%S')


def read_text(path):
    return path.read_text(encoding='utf-8', errors='ignore')


def backup_file_once(path, label):
    if not path.exists():
        return None

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    target = BACKUP_DIR / f'{path.name}.{label}.bak'
    if not target.exists():
        shutil.copy2(path, target)
    return target


def set_ini_value_lines(text, section, key, value):
    lines = text.splitlines()
    output = []
    in_section = False
    section_found = False
    key_written = False

    for line in lines:
        stripped = line.strip()
        is_section = stripped.startswith('[') and stripped.endswith(']')
        if is_section:
            if in_section and not key_written:
                output.append(f'{key}={value}')
                key_written = True
            current = stripped[1:-1].strip()
            in_section = current.lower() == section.lower()
            section_found = section_found or in_section
        elif in_section and '=' in stripped:
            current_key = stripped.split('=', 1)[0].strip()
            if current_key.lower() == key.lower():
                output.append(f'{key}={value}')
                key_written = True
                continue
        output.append(line)

    if in_section and not key_written:
        output.append(f'{key}={value}')
        key_written = True

    if not section_found:
        if output and output[-1].strip():
            output.append('')
        output.extend([f'[{section}]', f'{key}={value}'])

    return '\r\n'.join(output) + '\r\n'


def is_generated_rules_file(path):
    if not path.exists():
        return False
    try:
        return read_text(path).startswith(RANDOMIZER_RULES_MARKER)
    except OSError:
        return False


def is_generated_hooked_map(path):
    if not path.exists():
        return False
    try:
        with path.open('r', encoding='utf-8', errors='ignore') as handle:
            return handle.readline().strip() == HOOKED_MAP_MARKER
    except OSError:
        return False


def sanitize_marker_part(value, max_length=12):
    cleaned = re.sub(r'[^A-Za-z0-9]', '', value or '').upper()
    return (cleaned or 'UNK')[:max_length]


def find_section_bounds(lines, section):
    wanted = section.lower()
    start = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            if start is not None:
                return (start, index)
            if stripped[1:-1].strip().lower() == wanted:
                start = index
    if start is None:
        return (None, None)
    return (start, len(lines))


def find_all_section_bounds(lines, section):
    wanted = section.lower()
    matches = []
    start = None
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            if start is not None:
                matches.append((start, index))
                start = None
            if stripped[1:-1].strip().lower() == wanted:
                start = index
    if start is not None:
        matches.append((start, len(lines)))
    return matches


def section_lines(lines, section):
    start, end = find_section_bounds(lines, section)
    if start is None:
        return []
    return lines[start + 1:end]


def section_names(lines):
    names = []
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            names.append(stripped[1:-1].strip())
    return names


def section_value_map(lines, section):
    values = {}
    for line in section_lines(lines, section):
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        values[key.strip().lower()] = value.strip()
    return values


def section_value_map_preserve(lines, section):
    values = {}
    for line in section_lines(lines, section):
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        values[key.strip()] = value.strip()
    return values


def all_section_value_maps(lines):
    sections = {}
    current = None
    current_values = None
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            current = stripped[1:-1].strip()
            current_values = {}
            sections[current] = current_values
            continue
        if current_values is not None and '=' in line:
            key, value = line.split('=', 1)
            current_values[key.strip().lower()] = value.strip()
    return sections


def next_numeric_section_index(lines, section):
    highest = -1
    for line in section_lines(lines, section):
        if '=' not in line:
            continue
        key = line.split('=', 1)[0].strip()
        if key.isdigit():
            highest = max(highest, int(key))
    return highest + 1


def append_section_list_entry(lines, section, value):
    start, end = find_section_bounds(lines, section)
    if start is None:
        if lines and lines[-1].strip():
            lines.append('')
        lines.extend([f'[{section}]', f'0={value}'])
        return

    index = next_numeric_section_index(lines, section)
    lines.insert(end, f'{index}={value}')


def parse_action_groups(value):
    tokens = [token.strip() for token in value.split(',')]
    if not tokens:
        return (0, [])
    try:
        count = int(tokens[0])
    except ValueError:
        return (0, [])
    groups = []
    cursor = 1
    while cursor + 7 < len(tokens):
        groups.append(tokens[cursor:cursor + 8])
        cursor += 8
    return (count, groups)


def action_group_tokens(groups):
    return [token for group in groups for token in group]


def tech_ids_for_rewards(rewards):
    tech_ids = set()
    for reward in rewards:
        reward = canonical_reward(reward)
        for section, values in reward.get('rules', {}).items():
            if any(key.lower() == 'techlevel' for key in values):
                tech_ids.add(section.upper())
    return tech_ids


def unlocked_reward_tech_ids(rewards):
    tech_ids = set()
    for reward in canonical_rewards(rewards):
        if reward.get('kind') == 'buff':
            continue
        tech_ids.update(tech_ids_for_rewards([reward]))
    return tech_ids


def buffs_with_unlocked_access(rewards, require_unlocked_access=True):
    unlocked = unlocked_reward_tech_ids(rewards)
    filtered = []
    for reward in canonical_rewards(rewards):
        if reward.get('kind') != 'buff':
            filtered.append(reward)
            continue
        unit_id = (reward.get('unit') or '').upper()
        if not require_unlocked_access or reward.get('global_buff') or not unit_id or unit_id in unlocked:
            filtered.append(reward)
    return filtered


def remove_locked_techlevel_actions(lines, unlocked_tech_ids):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return 0

    controlled = {section.upper() for section in controlled_tech_ids()}
    unlocked = {section.upper() for section in unlocked_tech_ids}
    removed = 0

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue

        key, value = line.split('=', 1)
        count, groups = parse_action_groups(value)
        if not count or not groups:
            continue

        kept = []
        for group in groups:
            if len(group) >= 3 and group[0] == '106':
                tech_id = group[2].strip().upper()
                if tech_id in controlled and tech_id not in unlocked:
                    removed += 1
                    continue
            kept.append(group)

        if len(kept) != len(groups):
            tokens = action_group_tokens(kept)
            lines[index] = f'{key.strip()}={len(kept)}' + (',' + ','.join(tokens) if tokens else '')

    return removed


def action_has_code(groups, code):
    return any(group and group[0] == str(code) for group in groups)


def action_has_objective_complete(groups):
    for group in groups:
        if len(group) < 3:
            continue
        action_code = group[0]
        parameter = group[2].lower()
        if action_code == '19' and parameter == 'objectivecomplete':
            return True
        if action_code == '21' and parameter == 'eva_objectivecomplete':
            return True
        if action_code == '11' and parameter == 'mission:objc':
            return True
    return False


def techlevel_action_tokens(section, level):
    return ['106', '9', section, '0', '0', '0', '0', str(level)]


def techlevel_actions_for_reward(reward):
    reward = canonical_reward(reward)
    actions = []
    for section, values in reward.get('rules', {}).items():
        for key, value in values.items():
            if key.lower() == 'techlevel':
                actions.append(techlevel_action_tokens(section, UNLOCKED_TECH_LEVEL))
    return actions


def techlevel_actions_for_rewards(rewards):
    actions = []
    for reward in canonical_rewards(rewards):
        actions.extend(techlevel_actions_for_reward(reward))
    return actions


def techlevel_rules_for_reward(reward):
    reward = canonical_reward(reward)
    rule_sections = {}
    for section, values in reward.get('rules', {}).items():
        for key, value in values.items():
            if key.lower() == 'techlevel':
                rule_sections.setdefault(section, {})[key] = UNLOCKED_TECH_LEVEL
            else:
                rule_sections.setdefault(section, {})[key] = value
    return rule_sections


def launch_rules_for_reward(reward):
    reward = canonical_reward(reward)
    if reward.get('kind') == 'buff':
        return {
            section: dict(values)
            for section, values in reward.get('rules', {}).items()
        }
    return techlevel_rules_for_reward(reward)


def parse_float(value, default=1.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def format_multiplier(value):
    return f'{value:.3f}'.rstrip('0').rstrip('.')


def comma_items(value):
    return [item.strip() for item in (value or '').split(',') if item.strip()]


def merge_unique_csv(existing, additions):
    merged = []
    seen = set()
    for item in comma_items(existing) + list(additions):
        key = item.upper()
        if key in seen:
            continue
        seen.add(key)
        merged.append(item)
    return ','.join(merged)


def stacked_house_buff_values(rewards, base_values=None, require_unlocked_access=True):
    base_values = base_values or {}
    category_counts = {}
    veteran_units = {}
    rof_count = 0

    for reward in buffs_with_unlocked_access(rewards, require_unlocked_access=require_unlocked_access):
        if reward.get('kind') != 'buff' or not reward.get('unit') or not reward.get('buff_type'):
            continue
        buff_type = reward.get('buff_type')
        if buff_type not in HOUSE_SCOPED_BUFF_TYPES:
            continue
        target = BUFF_TARGETS.get(reward.get('unit'))
        if not target:
            continue
        if buff_type == 'production' and target.get('global_production'):
            for global_suffix in ('Infantry', 'Units', 'Aircraft', 'Buildings', 'Defenses'):
                key = (buff_type, global_suffix)
                category_counts[key] = category_counts.get(key, 0) + 1
            continue
        suffix = house_category_suffix(target)
        if buff_type == 'rof':
            rof_count += 1
            continue
        if buff_type == 'veteran':
            # Ares calls the country flag VeteranBuildings, including for
            # defenses. VeteranDefenses is not an engine key.
            if target.get('category') == 'defenses':
                if not target.get('trainable'):
                    continue
                suffix = 'Buildings'
            veteran_units.setdefault(suffix, []).append(reward['unit'])
            continue
        category_counts[(buff_type, suffix)] = category_counts.get((buff_type, suffix), 0) + 1

    values = {}
    for (buff_type, suffix), count in category_counts.items():
        if buff_type == 'production':
            key = f'BuildTime{suffix}Mult'
            multiplier = max(0.35, 0.85 ** count)
        elif buff_type == 'cost':
            key = f'Cost{suffix}Mult'
            multiplier = max(0.30, 0.80 ** count)
        elif buff_type == 'speed':
            key = f'Speed{suffix}Mult'
            multiplier = min(1.75, 1.10 ** count)
        elif buff_type == 'armor':
            key = f'Armor{suffix}Mult'
            multiplier = max(0.50, 0.90 ** count)
        else:
            continue
        existing_key = next((key_name for key_name in base_values if key_name.lower() == key.lower()), key)
        base = parse_float(base_values.get(existing_key), 1.0)
        values[key] = format_multiplier(base * multiplier)

    if rof_count:
        base = parse_float(base_values.get('ROF'), 1.0)
        values['ROF'] = format_multiplier(base * max(0.40, 0.90 ** rof_count))

    for suffix, units in veteran_units.items():
        key = f'Veteran{suffix}'
        existing_key = next((key_name for key_name in base_values if key_name.lower() == key.lower()), key)
        values[key] = merge_unique_csv(base_values.get(existing_key, ''), units)

    return values


def taskforce_unit_usage_houses(lines, unit_id):
    unit_upper = (unit_id or '').upper()
    sections = all_section_value_maps(lines)
    taskforce_to_houses = {}
    for values in sections.values():
        taskforce = values.get('taskforce')
        house = values.get('house')
        if taskforce and house:
            taskforce_to_houses.setdefault(taskforce.lower(), set()).add(house)

    usage_houses = set()
    for taskforce_id, houses in taskforce_to_houses.items():
        for value in sections.get(taskforce_id, {}).values():
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and tokens[1].upper() == unit_upper:
                usage_houses.update(houses)
    return usage_houses


def placed_unit_usage_houses(lines, unit_id):
    unit_upper = (unit_id or '').upper()
    usage_houses = set()
    for section in ('Infantry', 'Units', 'Aircraft', 'Structures'):
        for line in section_lines(lines, section):
            if '=' not in line:
                continue
            _, value = line.split('=', 1)
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and tokens[1].upper() == unit_upper:
                usage_houses.add(tokens[0])
    return usage_houses


def unit_usage_houses(lines, unit_id):
    return placed_unit_usage_houses(lines, unit_id) | taskforce_unit_usage_houses(lines, unit_id)


# Installed Mental Omega 3.3.6 weapon-sharing relationships for buffable
# weapons. Weapon rules are global, so an enemy using a different TechnoType
# with the same weapon has to participate in the same safety check.
SHARED_WEAPON_USER_IDS = {
    'AGGATTLING': {'YAGGUN', 'YTNK'},
    'AGGATTLING2': {'YAGGUN', 'YTNK'},
    'ANTARESBEAM': {'YAHADE', 'YAHADEAI'},
    'ANTARESBEAMBLUE': {'YAHADE', 'YAHADEAI'},
    'HOWITZER': {'HOWI', 'AIHOWI'},
    'HOWITZERE': {'HOWI', 'AIHOWI'},
    'NEUTRALIZERCUTTER': {'FACOMP', 'FACOMPAI'},
    'REDEYE2': {'NASAM', 'NASAMT'},
}


def unit_weapon_buff_rules(lines, rewards, buff_allied_helpers=False, require_unlocked_access=True):
    player_house = player_house_from_map(lines)
    if not player_house:
        return ({}, [], [])

    player_houses = player_controlled_houses(lines) or [player_house]
    helper_houses = allied_helper_houses(lines, player_house) if buff_allied_helpers else []
    records = map_house_records(lines)
    allowed_names = []
    for house in unique_in_order(player_houses + helper_houses):
        record = records.get(house, {})
        allowed_names.append(house)
        allowed_names.append(house.replace(' House', ''))
        if record.get('country'):
            allowed_names.append(record['country'])
    allowed_houses = {name.lower() for name in allowed_names if name}
    grouped_counts = {}
    for reward in buffs_with_unlocked_access(rewards, require_unlocked_access=require_unlocked_access):
        if reward.get('kind') != 'buff':
            continue
        buff_type = reward.get('buff_type')
        if buff_type not in CLONE_REQUIRED_BUFF_TYPES:
            continue
        unit_id = reward.get('unit')
        target = BUFF_TARGETS.get(unit_id, {})
        if not unit_id or not target:
            continue
        if buff_type in WEAPON_STAT_BUFF_TYPES and not target.get('weapons'):
            continue
        if buff_type == 'health' and 'strength' not in target:
            continue
        if buff_type == 'sight' and 'sight' not in target:
            continue
        if buff_type == 'ammo' and 'ammo' not in target:
            continue
        if buff_type == 'guard_range' and 'guard_range' not in target:
            continue
        key = (unit_id, buff_type)
        grouped_counts[key] = grouped_counts.get(key, 0) + 1

    rule_sections = {}
    applied_units = []
    skipped_units = []
    for (unit_id, buff_type), count in grouped_counts.items():
        target = BUFF_TARGETS.get(unit_id, {})
        usage = unit_usage_houses(lines, unit_id)
        unsafe_houses = sorted(house for house in usage if house.lower() not in allowed_houses)
        if unsafe_houses:
            skipped_units.append(f'{target.get("label", unit_id)} ({", ".join(unsafe_houses)})')
            continue

        applied = False
        if buff_type in UNIT_STAT_BUFF_TYPES:
            values = rule_sections.setdefault(unit_id, {})
            if buff_type == 'health':
                multiplier = min(2.0, 1.15 ** count)
                values['Strength'] = str(max(1, int(round(target['strength'] * multiplier))))
            elif buff_type == 'sight':
                values['Sight'] = str(int(round(target['sight'] + min(4, count))))
            elif buff_type == 'ammo':
                values['Ammo'] = str(int(round(target['ammo'] + min(5, count))))
            elif buff_type == 'self_healing':
                values['SelfHealing'] = 'yes'
            elif buff_type == 'cloak':
                values['Cloakable'] = 'yes'
                values['Cloakable.Stages'] = '1'
                values['CloakingSpeed'] = '1'
                values['CloakSound'] = 'none'
            elif buff_type == 'sensors':
                values['Sensors'] = 'yes'
                values['SensorsSight'] = str(int(round(target.get('sight', 5) + 2)))
            elif buff_type == 'guard_range':
                values['GuardRange'] = format_multiplier(target['guard_range'] + min(5, count))
            applied = True

        if buff_type in WEAPON_STAT_BUFF_TYPES:
            for weapon, base_stats in target.get('weapons', {}).items():
                weapon_users = SHARED_WEAPON_USER_IDS.get(weapon.upper(), {unit_id})
                weapon_usage = set()
                for weapon_user in weapon_users:
                    weapon_usage.update(unit_usage_houses(lines, weapon_user))
                unsafe_weapon_houses = sorted(
                    house for house in weapon_usage if house.lower() not in allowed_houses
                )
                if unsafe_weapon_houses:
                    skipped_units.append(
                        f'{target.get("label", unit_id)} / {weapon} '
                        f'({", ".join(unsafe_weapon_houses)})'
                    )
                    continue
                values = rule_sections.setdefault(weapon, {})
                if buff_type == 'damage' and 'damage' in base_stats:
                    multiplier = min(2.0, 1.15 ** count)
                    values['Damage'] = str(max(1, int(round(base_stats['damage'] * multiplier))))
                    applied = True
                elif buff_type == 'range' and 'range' in base_stats:
                    values['Range'] = format_multiplier(base_stats['range'] + min(3.0, 0.5 * count))
                    applied = True
                elif buff_type == 'reload' and 'rof' in base_stats:
                    multiplier = max(0.45, 0.90 ** count)
                    values['ROF'] = str(max(1, int(round(base_stats['rof'] * multiplier))))
                    applied = True
        if applied:
            applied_units.append(target.get('label', unit_id))

    return (rule_sections, unique_in_order(applied_units), unique_in_order(skipped_units))


def controlled_tech_ids():
    tech_ids = set(EXTRA_TECH_LOCKS)
    for reward in REWARD_POOL:
        tech_ids.update(techlevel_rules_for_reward(reward))
    return tech_ids - {tech_id.upper() for tech_id in ALWAYS_AVAILABLE_TECH_IDS}


def reward_unlock_tech_ids():
    tech_ids = set()
    for reward in REWARD_POOL:
        if reward.get('kind') == 'buff':
            continue
        tech_ids.update(techlevel_rules_for_reward(reward))
    return tech_ids


def action_line_ids(lines, predicate):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return []

    ids = []
    for line in lines[start + 1:end]:
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        count, groups = parse_action_groups(value)
        if count and predicate(groups):
            ids.append(key.strip())
    return ids


def trigger_action_ids_by_name(lines, patterns):
    start, end = find_section_bounds(lines, 'Triggers')
    if start is None:
        return []

    lowered_patterns = [pattern.lower() for pattern in patterns]
    action_start, _ = find_section_bounds(lines, 'Actions')
    if action_start is None:
        return []
    action_ids = {
        line.split('=', 1)[0].strip().lower()
        for line in section_lines(lines, 'Actions')
        if '=' in line
    }

    ids = []
    for line in lines[start + 1:end]:
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        if key.lower() not in action_ids:
            continue
        value_lower = value.lower()
        if any(pattern in value_lower for pattern in lowered_patterns):
            ids.append(key)
    return ids


def unique_in_order(items):
    seen = set()
    result = []
    for item in items:
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def player_country_from_map(lines):
    house = player_house_from_map(lines)
    if house:
        house_values = section_value_map(lines, house)
        return house_values.get('country') or house.replace(' House', '')
    return 'UnitedStates'


def player_house_from_map(lines):
    for house_name in section_lines(lines, 'Houses'):
        if '=' not in house_name:
            continue
        _, value = house_name.split('=', 1)
        section = value.strip()
        house_values = section_value_map(lines, section)
        if house_values.get('playercontrol', '').lower() == 'yes':
            return section
    return ''


def player_controlled_houses(lines):
    houses = []
    for house_name in section_lines(lines, 'Houses'):
        if '=' not in house_name:
            continue
        _, value = house_name.split('=', 1)
        section = value.strip()
        house_values = section_value_map(lines, section)
        if house_values.get('playercontrol', '').lower() == 'yes':
            houses.append(section)
    return unique_in_order(houses)


def clone_player_country_for_house_buffs(lines, rewards, require_unlocked_access=True):
    player_house = player_house_from_map(lines)
    if not player_house:
        return ('', {})

    house_values = section_value_map(lines, player_house)
    original_country = house_values.get('country') or player_house.replace(' House', '')
    original_values = section_value_map_preserve(lines, original_country)
    house_buff_values = stacked_house_buff_values(
        rewards,
        original_values,
        require_unlocked_access=require_unlocked_access,
    )
    if not house_buff_values:
        return (player_house, {})

    cloned_country = 'MORPLAYER'
    country_values = dict(original_values)
    country_values.update({
        'Name': cloned_country,
        'ParentCountry': original_country,
    })
    country_values.update(house_buff_values)

    countries = [
        line.split('=', 1)[1].strip().lower()
        for line in section_lines(lines, 'Countries')
        if '=' in line
    ]
    if cloned_country.lower() not in countries:
        append_section_list_entry(lines, 'Countries', cloned_country)

    merge_ini_section_values(lines, {
        cloned_country: country_values,
        player_house: {'Country': cloned_country},
    })
    return (player_house, house_buff_values)


def houses_for_country(lines, country):
    matches = []
    wanted = (country or '').strip().lower()
    if not wanted:
        return matches

    for house_name in section_lines(lines, 'Houses'):
        if '=' not in house_name:
            continue
        _, value = house_name.split('=', 1)
        section = value.strip()
        house_values = section_value_map(lines, section)
        house_country = house_values.get('country') or section.replace(' House', '')
        if house_country.strip().lower() != wanted:
            continue
        matches.append({
            'name': section,
            'player': house_values.get('playercontrol', '').lower() == 'yes',
        })
    return matches


def country_inherits_from(lines, country, ancestor):
    wanted = (ancestor or '').strip().lower()
    current = (country or '').strip()
    visited = set()
    while current and current.lower() not in visited:
        current_lower = current.lower()
        if current_lower == wanted:
            return True
        visited.add(current_lower)
        values = section_value_map(lines, current)
        parent = values.get('parentcountry', '').strip()
        if not parent or parent.lower() == current_lower:
            break
        current = parent
    return False


def house_names(lines):
    names = []
    for house_name in section_lines(lines, 'Houses'):
        if '=' not in house_name:
            continue
        _, value = house_name.split('=', 1)
        name = value.strip()
        if name:
            names.append(name)
    return unique_in_order(names)


def map_house_records(lines):
    records = {}
    for name in house_names(lines):
        values = section_value_map(lines, name)
        country = values.get('country') or name.replace(' House', '')
        country_values = section_value_map(lines, country)
        records[name] = {
            'name': name,
            'country': country,
            'parent_country': country_values.get('parentcountry', ''),
            'side': country_values.get('side', ''),
            'allies': comma_items(values.get('allies', '')),
            'player': values.get('playercontrol', '').lower() == 'yes',
        }
    return records


def is_buffable_helper_house(record):
    name = (record.get('name') or '').lower()
    country = (record.get('country') or '').lower()
    parent = (record.get('parent_country') or '').lower()
    blocked = ('neutral', 'civilian', 'special', 'placeholder', 'cinematic')
    if parent in blocked:
        return False
    return not any(token in name or token in country for token in blocked)


def country_family(record):
    text = ' '.join([
        record.get('name') or '',
        record.get('country') or '',
        record.get('parent_country') or '',
        record.get('side') or '',
    ]).lower()
    country_text = ' '.join([
        record.get('name') or '',
        record.get('country') or '',
        record.get('parent_country') or '',
    ]).lower()

    if 'fourthside' in text:
        return 'foehn'
    if any(token in country_text for token in (
        'foehn', 'coronia', 'haiheadquarters', 'hai_headquarters', 'lastbastion'
    )):
        return 'foehn'
    if (
        any(token in country_text for token in ('guild1', 'guild2', 'guild3'))
        and 'europeans' not in country_text
    ):
        return 'foehn'
    if any(token in country_text for token in (
        'psicorps', 'psi_corps', 'scorpion', 'epsilon', 'yuri', 'headquaters'
    )):
        return 'epsilon'
    if any(token in country_text for token in (
        'ussr', 'soviet', 'russia', 'latin', 'chinese', 'iraq', 'cuba', 'libya'
    )):
        return 'soviets'
    if any(token in country_text for token in (
        'unitedstates', 'europeans', 'euro_alliance', 'pacific', 'guild'
    )):
        return 'allies'
    if 'thirdside' in text:
        return 'epsilon'
    if 'nod' in text:
        return 'soviets'
    if 'gdi' in text:
        return 'allies'
    return ''


def same_helper_family(player_record, helper_record):
    player_family = country_family(player_record)
    helper_family = country_family(helper_record)
    if not player_family or not helper_family:
        return False
    if player_family == 'foehn' and helper_family in {'allies', 'soviets', 'foehn'}:
        player_allies = {name.lower() for name in player_record.get('allies', [])}
        helper_allies = {name.lower() for name in helper_record.get('allies', [])}
        return (
            helper_record.get('name', '').lower() in player_allies
            and player_record.get('name', '').lower() in helper_allies
        )
    return player_family == helper_family


def allied_helper_houses(lines, player_house):
    records = map_house_records(lines)
    player_record = records.get(player_house)
    if not player_record:
        return []

    player_allies = {name.lower() for name in player_record.get('allies', [])}
    helpers = []
    for name, record in records.items():
        if name.lower() == player_house.lower() or record.get('player'):
            continue
        record_allies = {ally.lower() for ally in record.get('allies', [])}
        if name.lower() not in player_allies and player_house.lower() not in record_allies:
            continue
        if not is_buffable_helper_house(record):
            continue
        helpers.append(name)
    return unique_in_order(helpers)


def unsafe_country_houses(lines, country, allowed_house_names):
    allowed = {name.lower() for name in allowed_house_names}
    unsafe = []
    for name, record in map_house_records(lines).items():
        if not country_inherits_from(lines, record.get('country'), country):
            continue
        if name.lower() not in allowed:
            unsafe.append(name)
    return unsafe


def player_country_buff_rules(
    lines,
    rewards,
    allow_shared_country=False,
    buff_allied_helpers=False,
    require_unlocked_access=True,
):
    player_house = player_house_from_map(lines)
    if not player_house:
        return ('', '', {}, [], [], [])

    player_houses = player_controlled_houses(lines) or [player_house]
    house_values = section_value_map(lines, player_house)
    player_country = house_values.get('country') or player_house.replace(' House', '')
    helper_houses = allied_helper_houses(lines, player_house) if buff_allied_helpers else []
    allowed_houses = unique_in_order(player_houses + helper_houses)
    shared_houses = unsafe_country_houses(lines, player_country, allowed_houses)

    rule_sections = {}
    buffed_helpers = []
    skipped_helpers = []
    if not shared_houses or allow_shared_country:
        original_values = section_value_map_preserve(lines, player_country)
        house_buff_values = stacked_house_buff_values(
            rewards,
            original_values,
            require_unlocked_access=require_unlocked_access,
        )
        if house_buff_values:
            rule_sections[player_country] = house_buff_values

    if buff_allied_helpers:
        records = map_house_records(lines)
        helper_clones = {}
        for helper in helper_houses:
            helper_country = records.get(helper, {}).get('country') or helper.replace(' House', '')
            if helper_country.lower() == player_country.lower():
                if player_country in rule_sections:
                    buffed_helpers.append(helper)
                else:
                    skipped_helpers.append(helper)
                continue

            unsafe_houses = unsafe_country_houses(lines, helper_country, allowed_houses)
            if unsafe_houses and not allow_shared_country:
                cloned_country = helper_clones.get(helper_country.lower())
                if not cloned_country:
                    clone_index = len(helper_clones) + 1
                    cloned_country = f'MORALLY{clone_index}'
                    existing_countries = {
                        line.split('=', 1)[1].strip().lower()
                        for line in section_lines(lines, 'Countries')
                        if '=' in line
                    }
                    while cloned_country.lower() in existing_countries:
                        clone_index += 1
                        cloned_country = f'MORALLY{clone_index}'
                    original_values = section_value_map_preserve(lines, helper_country)
                    helper_buff_values = stacked_house_buff_values(
                        rewards,
                        original_values,
                        require_unlocked_access=require_unlocked_access,
                    )
                    if not helper_buff_values:
                        skipped_helpers.append(helper)
                        continue
                    clone_values = dict(original_values)
                    clone_values.update({
                        'Name': cloned_country,
                        'ParentCountry': helper_country,
                    })
                    clone_values.update(helper_buff_values)
                    append_section_list_entry(lines, 'Countries', cloned_country)
                    rule_sections[cloned_country] = clone_values
                    helper_clones[helper_country.lower()] = cloned_country
                rule_sections[helper] = {'Country': cloned_country}
                buffed_helpers.append(helper)
                continue

            original_values = section_value_map_preserve(lines, helper_country)
            helper_buff_values = stacked_house_buff_values(
                rewards,
                original_values,
                require_unlocked_access=require_unlocked_access,
            )
            if helper_buff_values:
                rule_sections[helper_country] = helper_buff_values
                buffed_helpers.append(helper)

    return (player_house, player_country, rule_sections, shared_houses, buffed_helpers, skipped_helpers)


def append_action_to_action_id(lines, action_id, action_tokens):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return False

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        if key.strip().lower() != action_id.lower():
            continue
        tokens = [token.strip() for token in value.split(',')]
        try:
            tokens[0] = str(int(tokens[0]) + 1)
        except (ValueError, IndexError):
            return False
        tokens.extend(action_tokens)
        lines[index] = f'{key}={",".join(tokens)}'
        return True
    return False


def merge_ini_section_values(lines, section_values):
    for section, values in section_values.items():
        start, end = find_section_bounds(lines, section)
        if start is None:
            if lines and lines[-1].strip():
                lines.append('')
            lines.append(f'[{section}]')
            for key, value in sorted(values.items()):
                lines.append(f'{key}={value}')
            continue

        existing_keys = {}
        for index in range(start + 1, end):
            line = lines[index]
            if '=' not in line:
                continue
            key = line.split('=', 1)[0].strip().lower()
            existing_keys[key] = index

        insert_at = end
        inserted = 0
        for key, value in sorted(values.items()):
            existing_index = existing_keys.get(key.lower())
            if existing_index is not None:
                lines[existing_index] = f'{key}={value}'
            else:
                lines.insert(insert_at + inserted, f'{key}={value}')
                inserted += 1


def append_hook_team(lines, team_id, taskforce_id, script_id, marker_name, house):
    append_section_list_entry(lines, 'TaskForces', taskforce_id)
    append_section_list_entry(lines, 'ScriptTypes', script_id)
    append_section_list_entry(lines, 'TeamTypes', team_id)

    lines.extend([
        '',
        f'[{taskforce_id}]',
        f'Name={marker_name} Empty',
        'Group=-1',
        '',
        f'[{script_id}]',
        '0=11,5',
        f'Name={marker_name} Guard',
        '',
        f'[{team_id}]',
        'Max=1',
        'Full=no',
        f'Name={marker_name}',
        'Group=-1',
        f'House={house}',
        f'Script={script_id}',
        'Whiner=no',
        'Droppod=no',
        'Suicide=no',
        'Loadable=no',
        'Prebuild=no',
        'Priority=1',
        'Waypoint=A',
        'Annoyance=no',
        'IonImmune=no',
        'Recruiter=yes',
        'Reinforce=no',
        f'TaskForce={taskforce_id}',
        'TechLevel=0',
        'Aggressive=no',
        'Autocreate=no',
        'GuardSlower=no',
        'OnTransOnly=no',
        'AvoidThreats=no',
        'LooseRecruit=no',
        'VeteranLevel=1',
        'IsBaseDefense=no',
        'UseTransportOrigin=no',
        'MindControlDecision=0',
        'OnlyTargetHouseEnemy=no',
        'TransportsReturnOnUnload=no',
        'AreTeamMembersRecruitable=no',
    ])


def hook_marker_name(mission_code, check_id):
    if check_id == 'victory':
        suffix = 'VIC'
    else:
        suffix = sanitize_marker_part(check_id.replace('objective_', 'O'), 5)
    return f'MOR_{sanitize_marker_part(mission_code, 10)}_{suffix}'
