"""Map and INI patching helpers for the Mental Omega randomizer launcher."""
import re
import shutil
from datetime import datetime

from randomizer_ini import (
    action_group_tokens,
    all_section_value_maps,
    append_section_entry,
    append_section_list_entry,
    find_section_bounds,
    merge_ini_section_values,
    parse_action_groups,
    read_text,
    section_lines,
    section_value_map,
    section_value_map_preserve,
)
from randomizer_paths import BACKUP_DIR
from randomizer_rewards import (
    ALWAYS_AVAILABLE_UNIT_IDS,
    ALWAYS_AVAILABLE_TECH_IDS,
    BUFF_TARGETS,
    CLONE_REQUIRED_BUFF_TYPES,
    HOUSE_SCOPED_BUFF_TYPES,
    FACTION_UNIT_ROSTERS,
    REWARD_POOL,
    WEAPON_STAT_BUFF_TYPES,
    canonical_reward,
    canonical_rewards,
    house_category_suffix,
    unit_role_equivalents,
)
from randomizer_weapon_stats import WEAPON_USER_IDS

HOOKED_MAP_MARKER = '; Generated by Mental Omega Randomizer Launcher objective hook'
COMMON_BUILD_TAB_TECH_LOCKS = {
    # These appear in INI/Map Code/No Bases.ini as broadly start/build-enabled
    # infantry or units. Most are not randomizer rewards yet, so keep them out
    # of player build tabs until we intentionally add them to the item pool.
    'ABRM', 'AHVYBOT2', 'AMC', 'ARCH', 'ARMA', 'BANE', 'BANE_N', 'BASS',
    'BFRT', 'BGGY', 'BLZZ', 'BOREK', 'BRUTE', 'BURA', 'CHRP', 'CHRTNK',
    'CNTR', 'COON', 'COVE', 'CTNK', 'DESOR', 'DEVI', 'DEVO', 'DRON',
    'DTRUCK', 'DUNE', 'EMPR', 'ENFO', 'ENTK', 'FLAMER', 'GHOST', 'GHTNK',
    'HARP', 'HCAN', 'HOWI', 'HUNTR', 'IDRAG', 'IVAN', 'JTNK', 'KINGS',
    'KTNK', 'MARA', 'MEGA', 'MGTK', 'MOTOR', 'MTNK', 'PHNT', 'PLAG',
    'PROME', 'QTNK', 'QUICK', 'RACC', 'RAIL', 'RAMW', 'RAVA', 'RIOT',
    'ROACH', 'ROBO', 'ROADR', 'SCAV', 'SDRN', 'SEITAAD', 'SHADOW',
    'SHRAY', 'SNIPE', 'SREF', 'STALKER', 'STING', 'STNK', 'SUPR',
    'TELE', 'TENGU', 'TNKKIL', 'TRACTOR', 'TRIKE', 'V3', 'VCARR',
    'YDOG', 'YURI', 'ZORB',
}
EXTRA_TECH_LOCKS = {
    # Common naval and mission-provided tech that can appear before the
    # randomizer has granted it. Keep this broader than the reward pool.
    'AEGIS', 'AKULA', 'CARRIER', 'DBOAT', 'DEST', 'DLPH', 'DRED', 'HCRUIS',
    'LCRF', 'SAPC', 'SQD', 'SUB', 'SUB2',
    # Extra Mental Omega tech seen in campaign spawn maps.
    'AERO', 'AICLEG', 'AITHOR', 'AMCV', 'BEAG', 'BLIGHT', 'CHRTNK', 'CRYO',
    'CRYOAI', 'DUST', 'FOX', 'GAGAP', 'GASTAS', 'GAWEAT', 'HBIRD', 'LIONH',
    'MWF', 'NAHAMM', 'NAINDP', 'NAIRDM', 'NAMISL', 'NASCOM', 'ORCA', 'RAVA',
    'REAP', 'ROBOW', 'SBTR', 'SEIZER', 'SHOCK', 'SIEG', 'SMCV', 'SPY', 'SREF',
    'STORM', 'THOR', 'VENOM', 'VOLKOV',
    # Soviet campaign combat tech that can appear in build tabs even when it
    # is not part of the current randomizer access pool.
    'APOC', 'DESO', 'HOWI', 'HTK', 'MAMM', 'V3', 'WOLF', 'ZEP',
    # Common Allied infantry/support units exposed by early campaign barracks.
    'E1', 'GGI', 'ADOG', 'AMEDIC', 'JUMPJET', 'ENFO', 'GHOST', 'SUPR', 'SNIPE',
} | COMMON_BUILD_TAB_TECH_LOCKS
SCRIPTED_TECH_LOCK_EXCLUSIONS = {
    # These can appear as campaign-critical scripted/pre-placed units. Hard
    # TechLevel locks can stop trigger-created teams from spawning, causing
    # immediate fail/win chains on missions such as Bad Apple.
    'ENFO', 'GHOST', 'SNIPE', 'SPY', 'SUPR', 'TANY', 'TANYA', 'VOLKOV',
    # Extra campaign combat tech that is not a randomizer access reward yet.
    # BuildLimit blocks player production while keeping scripted teams safer
    # than a hard TechLevel lock.
    'APOC', 'DESO', 'MAMM', 'WOLF', 'ZEP',
} | COMMON_BUILD_TAB_TECH_LOCKS
SCRIPTED_TECH_BUILD_LIMIT = '0'

RANDOMIZER_RULES_MARKER = '; Generated by Mental Omega Randomizer Launcher'
LOCKED_TECH_LEVEL = '11'
UNLOCKED_TECH_LEVEL = '1'
MISSION_ASSISTANCE_CATEGORIES = ('Infantry', 'Units', 'Aircraft')
MAX_MAP_ACTION_LINE_LENGTH = 511


def now_stamp():
    return datetime.now().strftime('%Y%m%d-%H%M%S')


def backup_file_once(path, label):
    if not path.exists():
        return None

    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    target = BACKUP_DIR / f'{path.name}.{label}.bak'
    if not target.exists():
        shutil.copy2(path, target)
    return target


def is_generated_rules_file(path):
    if not path.exists():
        return False
    try:
        return read_text(path).startswith(RANDOMIZER_RULES_MARKER)
    except OSError:
        return False


def is_generated_hooked_map(path):
    if not path.exists():
        return False
    try:
        with path.open('r', encoding='utf-8', errors='ignore') as handle:
            return handle.readline().strip() == HOOKED_MAP_MARKER
    except OSError:
        return False


def sanitize_marker_part(value, max_length=12):
    cleaned = re.sub(r'[^A-Za-z0-9]', '', value or '').upper()
    return (cleaned or 'UNK')[:max_length]


def tech_ids_for_rewards(rewards):
    tech_ids = set()
    for reward in rewards:
        reward = canonical_reward(reward)
        for section, values in reward.get('rules', {}).items():
            if any(key.lower() == 'techlevel' for key in values):
                tech_ids.add(section.upper())
    return tech_ids


def unlocked_reward_tech_ids(rewards):
    tech_ids = set()
    for reward in canonical_rewards(rewards):
        if reward.get('kind') == 'buff':
            continue
        tech_ids.update(tech_ids_for_rewards([reward]))
    return tech_ids


def buffs_with_unlocked_access(
    rewards,
    require_unlocked_access=True,
    additional_unlocked_tech_ids=None,
    share_basic_equivalent_buffs=False,
):
    unlocked = unlocked_reward_tech_ids(rewards)
    unlocked.update(
        str(unit_id).upper()
        for unit_id in (additional_unlocked_tech_ids or [])
    )
    filtered = []
    for reward in canonical_rewards(rewards):
        if reward.get('kind') != 'buff':
            filtered.append(reward)
            continue
        unit_id = (reward.get('unit') or '').upper()
        equivalents = unit_role_equivalents(unit_id)
        equivalent_is_unlocked = (
            share_basic_equivalent_buffs
            and len(equivalents) > 1
            and bool(unlocked.intersection(equivalents))
        )
        if (
            not require_unlocked_access
            or reward.get('global_buff')
            or not unit_id
            or unit_id in unlocked
            or equivalent_is_unlocked
        ):
            filtered.append(reward)
    return filtered


def expand_equivalent_role_buffs(rewards, enabled=False):
    """Apply each active unit buff to explicit cross-faction role peers."""
    if not enabled:
        return list(rewards)
    expanded = []
    for reward in rewards:
        expanded.append(reward)
        if reward.get('kind') != 'buff' or reward.get('mission_assistance'):
            continue
        for unit_id in sorted(unit_role_equivalents(reward.get('unit'))):
            if unit_id == reward.get('unit'):
                continue
            equivalent = dict(reward)
            equivalent['unit'] = unit_id
            expanded.append(equivalent)
    return expanded


def remove_locked_techlevel_actions(lines, unlocked_tech_ids, randomized_tech_ids=None):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return 0

    controlled = {
        section.upper()
        for section in (
            controlled_tech_ids() if randomized_tech_ids is None else randomized_tech_ids
        )
    }
    unlocked = {section.upper() for section in unlocked_tech_ids}
    removed = 0

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue

        key, value = line.split('=', 1)
        count, groups = parse_action_groups(value)
        if not count or not groups:
            continue

        kept = []
        for group in groups:
            if len(group) >= 3 and group[0] == '106':
                tech_id = group[2].strip().upper()
                if tech_id in controlled and tech_id not in unlocked:
                    removed += 1
                    continue
            kept.append(group)

        if len(kept) != len(groups):
            tokens = action_group_tokens(kept)
            lines[index] = f'{key.strip()}={len(kept)}' + (',' + ','.join(tokens) if tokens else '')

    return removed


def action_has_code(groups, code):
    return any(group and group[0] == str(code) for group in groups)


def action_has_objective_complete(groups):
    for group in groups:
        if len(group) < 3:
            continue
        action_code = group[0]
        parameter = group[2].lower()
        if action_code == '19' and parameter == 'objectivecomplete':
            return True
        if action_code == '21' and parameter == 'eva_objectivecomplete':
            return True
        if action_code == '11' and parameter == 'mission:objc':
            return True
    return False


def superweapon_actions_for_rewards(rewards):
    actions = []
    seen = set()
    for reward in canonical_rewards(rewards):
        if reward.get('kind') != 'superweapon':
            continue
        try:
            index = int(reward.get('superweapon_index'))
        except (TypeError, ValueError):
            continue
        if index < 0 or index in seen:
            continue
        seen.add(index)
        actions.append(['34', '0', str(index), '0', '0', '0', '0', 'A'])
    return actions


def superweapon_rule_sections_for_rewards(rewards):
    """Remove source-building and faction gates for earned power rewards.

    Action 34 creates a repeating House-owned power, but several support
    powers also declare their original subfaction, auxiliary building, or
    designator requirements in rulesmo.ini. Clearing only those availability
    gates lets the earned instance work for any player faction while retaining
    its real cost, recharge, targeting, inhibitors, and delivered objects.
    """
    sections = {}
    for reward in canonical_rewards(rewards):
        if reward.get('kind') != 'superweapon':
            continue
        superweapon = str(reward.get('superweapon') or '').strip()
        if not superweapon:
            continue
        overrides = reward.get('superweapon_rules')
        if not isinstance(overrides, dict) or not overrides:
            continue
        sections.setdefault(superweapon, {}).update(overrides)
    return sections


def techlevel_rules_for_reward(reward):
    reward = canonical_reward(reward)
    rule_sections = {}
    for section, values in reward.get('rules', {}).items():
        for key, value in values.items():
            if key.lower() == 'techlevel':
                rule_sections.setdefault(section, {})[key] = UNLOCKED_TECH_LEVEL
            else:
                rule_sections.setdefault(section, {})[key] = value
    return rule_sections


def launch_rules_for_reward(reward):
    reward = canonical_reward(reward)
    if reward.get('kind') == 'buff':
        return {
            section: dict(values)
            for section, values in reward.get('rules', {}).items()
        }
    return techlevel_rules_for_reward(reward)


def parse_float(value, default=1.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def format_multiplier(value):
    return f'{value:.3f}'.rstrip('0').rstrip('.')


def comma_items(value):
    return [item.strip() for item in (value or '').split(',') if item.strip()]


def merge_unique_csv(existing, additions):
    merged = []
    seen = set()
    for item in comma_items(existing) + list(additions):
        key = item.upper()
        if key in seen:
            continue
        seen.add(key)
        merged.append(item)
    return ','.join(merged)


def stacked_house_buff_values(
    rewards,
    base_values=None,
    require_unlocked_access=True,
    additional_unlocked_tech_ids=None,
    share_basic_equivalent_buffs=False,
    unit_specific_mode=False,
):
    base_values = base_values or {}
    category_counts = {}
    veteran_units = {}
    rof_count = 0

    for reward in buffs_with_unlocked_access(
        rewards,
        require_unlocked_access=require_unlocked_access,
        additional_unlocked_tech_ids=additional_unlocked_tech_ids,
        share_basic_equivalent_buffs=share_basic_equivalent_buffs,
    ):
        if reward.get('kind') != 'buff' or not reward.get('unit') or not reward.get('buff_type'):
            continue
        buff_type = reward.get('buff_type')
        if buff_type not in HOUSE_SCOPED_BUFF_TYPES:
            continue
        target = BUFF_TARGETS.get(reward.get('unit'))
        if not target:
            continue
        if (
            unit_specific_mode
            and buff_type in {'production', 'cost', 'speed', 'armor'}
            and not target.get('global_production')
        ):
            continue
        if buff_type == 'production' and target.get('global_production'):
            for global_suffix in ('Infantry', 'Units', 'Aircraft', 'Buildings', 'Defenses'):
                key = (buff_type, global_suffix)
                category_counts[key] = category_counts.get(key, 0) + 1
            continue
        suffix = house_category_suffix(target)
        if buff_type == 'rof':
            rof_count += 1
            continue
        if buff_type == 'veteran':
            # Ares calls the country flag VeteranBuildings, including for
            # defenses. VeteranDefenses is not an engine key.
            if target.get('category') == 'defenses':
                if not target.get('trainable'):
                    continue
                suffix = 'Buildings'
            units = (
                sorted(unit_role_equivalents(reward['unit']))
                if share_basic_equivalent_buffs
                else [reward['unit']]
            )
            for unit_id in units:
                equivalent_target = BUFF_TARGETS.get(unit_id, target)
                if (
                    equivalent_target.get('category') == 'defenses'
                    and not equivalent_target.get('trainable')
                ):
                    continue
                # Ares uses VeteranBuildings for trainable defenses. There is
                # no VeteranDefenses country key.
                equivalent_suffix = (
                    'Buildings'
                    if equivalent_target.get('category') == 'defenses'
                    else house_category_suffix(equivalent_target)
                )
                veteran_units.setdefault(equivalent_suffix, []).append(unit_id)
            continue
        suffixes = {suffix}
        if share_basic_equivalent_buffs:
            suffixes.update(
                house_category_suffix(BUFF_TARGETS[unit_id])
                for unit_id in unit_role_equivalents(reward['unit'])
                if unit_id in BUFF_TARGETS
            )
        for equivalent_suffix in suffixes:
            key = (buff_type, equivalent_suffix)
            category_counts[key] = category_counts.get(key, 0) + 1

    values = {}
    for (buff_type, suffix), count in category_counts.items():
        if buff_type == 'production':
            key = f'BuildTime{suffix}Mult'
            multiplier = max(0.35, 0.85 ** count)
        elif buff_type == 'cost':
            key = f'Cost{suffix}Mult'
            multiplier = max(0.30, 0.80 ** count)
        elif buff_type == 'speed':
            key = f'Speed{suffix}Mult'
            multiplier = min(1.75, 1.10 ** count)
        elif buff_type == 'armor':
            key = f'Armor{suffix}Mult'
            multiplier = max(0.50, 0.90 ** count)
        else:
            continue
        existing_key = next((key_name for key_name in base_values if key_name.lower() == key.lower()), key)
        base = parse_float(base_values.get(existing_key), 1.0)
        values[key] = format_multiplier(base * multiplier)

    if rof_count:
        base = parse_float(base_values.get('ROF'), 1.0)
        values['ROF'] = format_multiplier(base * max(0.40, 0.90 ** rof_count))

    for suffix, units in veteran_units.items():
        key = f'Veteran{suffix}'
        existing_key = next((key_name for key_name in base_values if key_name.lower() == key.lower()), key)
        values[key] = merge_unique_csv(base_values.get(existing_key, ''), units)

    return values


def mission_assistance_multipliers(stacks):
    """Return the cumulative player-only multipliers for failed-mission retries."""
    try:
        stacks = max(0, int(stacks))
    except (TypeError, ValueError):
        stacks = 0
    return {
        'production': max(0.35, 0.85 ** stacks),
        'cost': max(0.30, 0.80 ** stacks),
        'speed': min(1.75, 1.10 ** stacks),
        'armor': max(0.50, 0.90 ** stacks),
        'rof': max(0.40, 0.90 ** stacks),
        'health': min(2.0, 1.15 ** stacks),
        'damage': min(2.0, 1.15 ** stacks),
        'range': min(3.0, 0.5 * stacks),
    }


def mission_assistance_direct_rewards(unit_ids, stacks):
    """Build guarded health/damage/range buffs for accessible retry units.

    These stats live on global TechnoType/WeaponType sections rather than a
    country.  ``unit_weapon_buff_rules`` therefore remains responsible for
    rejecting a type whenever a non-assisted house uses it in this map.
    """
    try:
        stacks = max(0, int(stacks))
    except (TypeError, ValueError):
        stacks = 0
    rewards = []
    if not stacks:
        return rewards
    direct_stacks = min(stacks, 6)
    for unit_id in unique_in_order(
        str(unit_id or '').upper() for unit_id in (unit_ids or [])
    ):
        if unit_id not in BUFF_TARGETS:
            continue
        for _ in range(direct_stacks):
            for buff_type in ('health', 'damage', 'range'):
                rewards.append({
                    'kind': 'buff',
                    'unit': unit_id,
                    'buff_type': buff_type,
                    'global_buff': True,
                    'mission_assistance': True,
                })
    return rewards


def mission_assistance_buff_values(base_values, stacks):
    """Build category/country overrides for one mission's assistance stacks."""
    try:
        stacks = max(0, int(stacks))
    except (TypeError, ValueError):
        stacks = 0
    multipliers = mission_assistance_multipliers(stacks)
    if not stacks:
        return {}

    values = {}
    fields = (
        ('BuildTime', 'production'),
        ('Cost', 'cost'),
        ('Speed', 'speed'),
        ('Armor', 'armor'),
    )
    for prefix, multiplier_name in fields:
        for suffix in MISSION_ASSISTANCE_CATEGORIES:
            key = f'{prefix}{suffix}Mult'
            existing_key = next(
                (key_name for key_name in base_values if key_name.lower() == key.lower()),
                key,
            )
            base = parse_float(base_values.get(existing_key), 1.0)
            values[key] = format_multiplier(base * multipliers[multiplier_name])

    rof_key = next((key for key in base_values if key.lower() == 'rof'), 'ROF')
    values['ROF'] = format_multiplier(parse_float(base_values.get(rof_key), 1.0) * multipliers['rof'])
    return values


def mission_assistance_buff_rules(lines, stacks, buff_allied_helpers=False):
    """Scope retry assistance without changing a campaign house's country.

    Trigger owners in campaign maps are country IDs (for example ``Guild1``
    or ``UnitedStates``). Reassigning a house to a private clone disconnects
    every trigger owned by the original country and can break scripted unit
    transfers or the mission itself. Country-level assistance is therefore
    applied only when every house in that country family is an assisted house.
    Global unit/weapon assistance is guarded separately by
    :func:`unit_weapon_buff_rules`.
    """
    try:
        stacks = max(0, int(stacks))
    except (TypeError, ValueError):
        stacks = 0
    if not stacks:
        return ({}, [], [])

    records = map_house_records(lines)
    primary_house = player_house_from_map(lines, records=records)
    if not primary_house:
        return ({}, [], [])
    player_houses = player_controlled_houses(lines, records=records) or [primary_house]
    scripted_enemies = scripted_enemy_house_pairs(lines, records=records)
    transfer_houses = player_transfer_houses(
        lines,
        records=records,
        scripted_enemies=scripted_enemies,
    )
    helper_houses = (
        allied_helper_houses(
            lines,
            primary_house,
            records=records,
            transfer_houses=transfer_houses,
            scripted_enemies=scripted_enemies,
        )
        if buff_allied_helpers
        else []
    )
    assisted_houses = unique_in_order(player_houses + transfer_houses + helper_houses)
    usage_index = build_unit_usage_index(lines)
    country_houses = {}
    for house in assisted_houses:
        country = records.get(house, {}).get('country') or house.replace(' House', '')
        country_houses.setdefault(country, []).append(house)

    rule_sections = {}
    skipped_countries = []
    for country, houses in country_houses.items():
        original_values = section_value_map_preserve(lines, country)
        assistance_values = mission_assistance_buff_values(original_values, stacks)
        shared_houses = unsafe_country_houses(
            lines,
            country,
            assisted_houses,
            records=records,
            usage_index=usage_index,
            scripted_enemies=scripted_enemies,
        )
        if shared_houses:
            skipped_countries.append((country, list(houses), shared_houses))
            continue
        rule_sections[country] = assistance_values

    return (rule_sections, assisted_houses, skipped_countries)


def ai_trigger_team_usage_houses(lines):
    """Return the runtime owner overrides for TeamTypes used by AI triggers.

    FinalAlert commonly stores reusable TeamTypes with ``House=Neutral`` and
    supplies the real owner in ``[AITriggerTypes]``. Treating that placeholder
    as a live Neutral team incorrectly rejects friendly global unit buffs.
    """
    team_houses = {}
    for line in section_lines(lines, 'AITriggerTypes'):
        if '=' not in line:
            continue
        _, value = line.split('=', 1)
        tokens = [token.strip() for token in value.split(',')]
        if len(tokens) < 3:
            continue
        team_id = tokens[1]
        house = tokens[2]
        if not team_id or team_id.lower() in {'<none>', 'none'}:
            continue
        if not house or house.lower() in {'<none>', 'none'}:
            continue
        team_houses.setdefault(team_id.lower(), set()).add(house)
    return team_houses


def directly_created_team_ids(lines):
    """Return TeamTypes created directly by map actions instead of AI triggers."""
    team_ids = set()
    for line in section_lines(lines, 'Actions'):
        if '=' not in line:
            continue
        _, value = line.split('=', 1)
        _, groups = parse_action_groups(value)
        for group in groups:
            # Action 4 is Create Team; parameter 3 contains the TeamType ID.
            if group[0] == '4' and group[2]:
                team_ids.add(group[2].lower())
    return team_ids


def taskforce_usage_houses(lines, sections=None):
    """Resolve each TaskForce to the houses that can own it at runtime."""
    sections = sections or all_section_value_maps(lines)
    ai_team_houses = ai_trigger_team_usage_houses(lines)
    directly_created = directly_created_team_ids(lines)
    taskforce_to_houses = {}
    placeholder_houses = {'neutral', 'neutral house', '<none>', 'none'}
    for section_name, values in sections.items():
        taskforce = values.get('taskforce')
        house = values.get('house')
        if not taskforce or not house:
            continue

        section_key = section_name.lower()
        runtime_houses = ai_team_houses.get(section_key, set())
        houses = taskforce_to_houses.setdefault(taskforce.lower(), set())
        houses.update(runtime_houses)

        # A Neutral TeamType is a template when AITriggerTypes supplies the
        # actual owner. Keep Neutral only when the team can also be created
        # directly, or when no runtime owner override exists.
        if (
            house.lower() not in placeholder_houses
            or not runtime_houses
            or section_key in directly_created
        ):
            houses.add(house)
    return taskforce_to_houses


def taskforce_unit_usage_houses(lines, unit_id):
    unit_upper = (unit_id or '').upper()
    sections = all_section_value_maps(lines)
    sections_by_lower = {name.lower(): values for name, values in sections.items()}
    taskforce_to_houses = taskforce_usage_houses(lines, sections=sections)

    usage_houses = set()
    for taskforce_id, houses in taskforce_to_houses.items():
        for value in sections_by_lower.get(taskforce_id, {}).values():
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and tokens[1].upper() == unit_upper:
                usage_houses.update(houses)
    return usage_houses


def placed_unit_usage_houses(lines, unit_id):
    unit_upper = (unit_id or '').upper()
    usage_houses = set()
    for section in ('Infantry', 'Units', 'Aircraft', 'Structures'):
        for line in section_lines(lines, section):
            if '=' not in line:
                continue
            _, value = line.split('=', 1)
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and tokens[1].upper() == unit_upper:
                usage_houses.add(tokens[0])
    return usage_houses


def build_unit_usage_index(lines):
    """Index placed and scripted unit ownership with one map parse.

    Direct buffs may inspect hundreds of unit and shared-weapon users. Parsing
    every large campaign map once per lookup caused multi-second launch stalls.
    The index preserves the same ownership rules while making later lookups
    constant-time.
    """
    usage = {}
    sections = all_section_value_maps(lines)
    sections_by_lower = {name.lower(): values for name, values in sections.items()}
    for section in ('Infantry', 'Units', 'Aircraft', 'Structures'):
        for value in sections_by_lower.get(section.lower(), {}).values():
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2:
                usage.setdefault(tokens[1].upper(), set()).add(tokens[0])

    for taskforce_id, houses in taskforce_usage_houses(lines, sections=sections).items():
        for value in sections_by_lower.get(taskforce_id, {}).values():
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2:
                usage.setdefault(tokens[1].upper(), set()).update(houses)
    return usage


def unit_usage_houses(lines, unit_id, usage_index=None):
    if usage_index is not None:
        return set(usage_index.get(str(unit_id or '').upper(), set()))
    return placed_unit_usage_houses(lines, unit_id) | taskforce_unit_usage_houses(lines, unit_id)


def mission_assistance_unit_ids(
    lines,
    unlocked_unit_ids=None,
    additional_unit_ids=None,
    randomized_access=True,
    fallback_faction='',
    buff_allied_helpers=False,
):
    """Return units the player can use through progression or this mission.

    Randomized-access runs use earned/always-available units plus units placed
    or scripted for the player in this map. Buffs-only runs additionally show
    the complete normal roster for the player faction.
    """
    combat_categories = {'infantry', 'units', 'aircraft'}

    def is_unit(unit_id):
        return BUFF_TARGETS.get(str(unit_id or '').upper(), {}).get('category') in combat_categories

    records = map_house_records(lines)
    player_houses = player_controlled_houses(lines, records=records)
    primary_house = player_house_from_map(lines, records=records)
    if not player_houses and primary_house:
        player_houses = [primary_house]
    scripted_enemies = scripted_enemy_house_pairs(lines, records=records)
    transfer_houses = player_transfer_houses(
        lines,
        records=records,
        scripted_enemies=scripted_enemies,
    )
    helper_houses = (
        allied_helper_houses(
            lines,
            primary_house,
            records=records,
            transfer_houses=transfer_houses,
            scripted_enemies=scripted_enemies,
        )
        if buff_allied_helpers and primary_house
        else []
    )

    allowed_names = set()
    for house in unique_in_order(player_houses + helper_houses + transfer_houses):
        record = records.get(house, {})
        allowed_names.update({
            house.lower(),
            house.replace(' House', '').lower(),
            (record.get('country') or '').lower(),
        })
    allowed_names.discard('')

    unit_ids = {
        str(unit_id).upper()
        for unit_id in (unlocked_unit_ids or [])
        if is_unit(unit_id)
    }
    unit_ids.update(
        str(unit_id).upper()
        for unit_id in (additional_unit_ids or [])
        if is_unit(unit_id)
    )

    # Include units already placed for the player. This is especially
    # important for the first mission, before any access rewards exist.
    for section in ('Infantry', 'Units', 'Aircraft'):
        for line in section_lines(lines, section):
            if '=' not in line:
                continue
            _, value = line.split('=', 1)
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and tokens[0].lower() in allowed_names and is_unit(tokens[1]):
                unit_ids.add(tokens[1].upper())

    # Include player-owned TaskForce units used by reinforcements and other
    # scripted teams, without repeatedly reparsing the whole map per roster ID.
    sections = all_section_value_maps(lines)
    sections_by_lower = {name.lower(): values for name, values in sections.items()}
    taskforce_owners = taskforce_usage_houses(lines, sections=sections)
    for taskforce, owners in taskforce_owners.items():
        if not {owner.lower() for owner in owners}.intersection(allowed_names):
            continue
        for value in sections_by_lower.get(taskforce, {}).values():
            tokens = [token.strip() for token in value.split(',')]
            if len(tokens) >= 2 and is_unit(tokens[1]):
                unit_ids.add(tokens[1].upper())

    family_names = {
        'allies': 'Allies',
        'soviets': 'Soviets',
        'epsilon': 'Epsilon',
        'foehn': 'Foehn',
    }
    player_factions = set()
    for house in player_houses:
        family = country_family(records.get(house, {}))
        if family in family_names:
            player_factions.add(family_names[family])
    if fallback_faction in FACTION_UNIT_ROSTERS:
        player_factions.add(fallback_faction)

    for faction in player_factions:
        roster_ids = {
            unit_id.upper()
            for category in FACTION_UNIT_ROSTERS.get(faction, {}).values()
            for unit_id in category
        }
        if randomized_access:
            roster_ids.intersection_update(ALWAYS_AVAILABLE_UNIT_IDS)
        unit_ids.update(unit_id for unit_id in roster_ids if is_unit(unit_id))

    return sorted(unit_ids)


# Installed Mental Omega 3.3.6 weapon-sharing relationships for every
# buffable roster weapon. Campaign-only and AI-only TechnoTypes participate in
# the enemy-safety check because WeaponType values are global.
SHARED_WEAPON_USER_IDS = {
    weapon_id: set(unit_ids)
    for weapon_id, unit_ids in WEAPON_USER_IDS.items()
}


def apply_unit_buff_value(values, target, buff_type, count):
    if buff_type == 'health':
        multiplier = min(2.0, 1.15 ** count)
        values['Strength'] = str(max(1, int(round(target['strength'] * multiplier))))
    elif buff_type == 'sight':
        values['Sight'] = str(int(round(target['sight'] + min(4, count))))
    elif buff_type == 'ammo':
        values['Ammo'] = str(int(round(target['ammo'] + min(5, count))))
    elif buff_type == 'self_healing':
        values['SelfHealing'] = 'yes'
    elif buff_type == 'cloak':
        values['Cloakable'] = 'yes'
        values['Cloakable.Stages'] = '1'
        values['CloakingSpeed'] = '1'
        values['CloakSound'] = 'none'
    elif buff_type == 'sensors':
        values['Sensors'] = 'yes'
        values['SensorsSight'] = str(int(round(target.get('sight', 5) + 2)))
    elif buff_type == 'cost':
        multiplier = max(0.30, 0.80 ** count)
        values['Cost'] = str(max(1, int(round(target['cost'] * multiplier))))
    elif buff_type == 'speed':
        multiplier = min(1.75, 1.10 ** count)
        values['Speed'] = str(max(1, int(round(target['speed'] * multiplier))))
    elif buff_type == 'armor':
        multiplier = max(0.50, 0.90 ** count)
        current_strength = int(values.get('Strength', target['strength']))
        values['Strength'] = str(max(1, int(round(current_strength / multiplier))))
    else:
        return False
    return True


def apply_weapon_buff_value(values, base_stats, buff_type, count):
    if buff_type == 'damage' and base_stats.get('damage', 0) > 0:
        multiplier = min(2.0, 1.15 ** count)
        base_damage = int(round(base_stats['damage']))
        values['Damage'] = str(max(base_damage + 1, int(round(base_damage * multiplier))))
    elif buff_type == 'range' and base_stats.get('range', 0) > 0:
        values['Range'] = format_multiplier(base_stats['range'] + min(3.0, 0.5 * count))
    elif buff_type == 'reload' and base_stats.get('rof', 0) > 1:
        multiplier = max(0.45, 0.90 ** count)
        values['ROF'] = str(max(1, int(round(base_stats['rof'] * multiplier))))
    else:
        return False
    return True


def unit_weapon_buff_rules(
    lines,
    rewards,
    buff_allied_helpers=False,
    require_unlocked_access=True,
    additional_unlocked_tech_ids=None,
    share_basic_equivalent_buffs=False,
    unit_specific_mode=False,
):
    """Apply direct buffs only when their global type is safe for friendly houses.

    TechnoType and WeaponType values are global in the engine. Keep the
    established safety guard here: player, allied-helper, and transfer houses
    participate; a direct buff is skipped if an enemy also uses the affected
    global type.
    """
    records = map_house_records(lines)
    player_house = player_house_from_map(lines, records=records)
    if not player_house:
        return ({}, [], [])

    player_houses = player_controlled_houses(lines, records=records) or [player_house]
    scripted_enemies = scripted_enemy_house_pairs(lines, records=records)
    transfer_houses = player_transfer_houses(
        lines,
        records=records,
        scripted_enemies=scripted_enemies,
    )
    helper_houses = (
        allied_helper_houses(
            lines,
            player_house,
            records=records,
            transfer_houses=transfer_houses,
            scripted_enemies=scripted_enemies,
        )
        if buff_allied_helpers else []
    )
    allowed_names = []
    for house in unique_in_order(player_houses + helper_houses + transfer_houses):
        record = records.get(house, {})
        if not record:
            record = records.get(house + ' House', {})
        allowed_names.append(house)
        allowed_names.append(house.replace(' House', ''))
        if not house.lower().endswith(' house'):
            allowed_names.append(house + ' House')
        if record.get('country'):
            allowed_names.append(record['country'])
    allowed_houses = {name.lower() for name in allowed_names if name}
    usage_index = build_unit_usage_index(lines)

    grouped_counts = {}
    active_rewards = buffs_with_unlocked_access(
        rewards,
        require_unlocked_access=require_unlocked_access,
        additional_unlocked_tech_ids=additional_unlocked_tech_ids,
        share_basic_equivalent_buffs=share_basic_equivalent_buffs,
    )
    for reward in expand_equivalent_role_buffs(
        active_rewards,
        enabled=share_basic_equivalent_buffs,
    ):
        if reward.get('kind') != 'buff':
            continue
        buff_type = reward.get('buff_type')
        direct_chaos_types = {'cost', 'speed', 'armor'} if unit_specific_mode else set()
        if buff_type not in CLONE_REQUIRED_BUFF_TYPES and buff_type not in direct_chaos_types:
            continue
        unit_id = reward.get('unit')
        target = BUFF_TARGETS.get(unit_id, {})
        if not unit_id or not target:
            continue
        if (
            buff_type in WEAPON_STAT_BUFF_TYPES
            and not target.get('weapons')
            and not (buff_type == 'damage' and target.get('special_damage_fields'))
        ):
            continue
        if buff_type == 'health' and 'strength' not in target:
            continue
        if buff_type == 'sight' and 'sight' not in target:
            continue
        if buff_type == 'ammo' and 'ammo' not in target:
            continue
        if buff_type == 'cost' and 'cost' not in target:
            continue
        if buff_type == 'speed' and 'speed' not in target:
            continue
        if buff_type == 'armor' and 'strength' not in target:
            continue
        key = (unit_id, buff_type)
        grouped_counts[key] = grouped_counts.get(key, 0) + 1

    counts_by_unit = {}
    for (unit_id, buff_type), count in grouped_counts.items():
        counts_by_unit.setdefault(unit_id, {})[buff_type] = count

    rule_sections = {}
    applied_units = []
    skipped_units = []
    for unit_id, counts in counts_by_unit.items():
        target = BUFF_TARGETS.get(unit_id, {})
        unsafe_unit_houses = sorted({
            house
            for house in unit_usage_houses(lines, unit_id, usage_index)
            if house.lower() not in allowed_houses
        })

        applied = False
        direct_types = set(counts) - WEAPON_STAT_BUFF_TYPES
        if unsafe_unit_houses and direct_types:
            skipped_units.append(
                f'{target.get("label", unit_id)} ({", ".join(unsafe_unit_houses)})'
            )
        elif direct_types:
            unit_values = rule_sections.setdefault(unit_id, {})
            for buff_type in (
                'health', 'armor', 'sight', 'ammo', 'self_healing', 'cloak',
                'sensors', 'cost', 'speed',
            ):
                if buff_type in counts and apply_unit_buff_value(
                    unit_values,
                    target,
                    buff_type,
                    counts[buff_type],
                ):
                    applied = True
            if not unit_values:
                rule_sections.pop(unit_id, None)

        weapon_buff_types = WEAPON_STAT_BUFF_TYPES.intersection(counts)
        if weapon_buff_types:
            for weapon, base_stats in target.get('weapons', {}).items():
                weapon_users = SHARED_WEAPON_USER_IDS.get(weapon.upper(), {unit_id})
                unsafe_weapon_houses = sorted({
                    house
                    for weapon_user in weapon_users
                    for house in unit_usage_houses(lines, weapon_user, usage_index)
                    if house.lower() not in allowed_houses
                })
                if unsafe_weapon_houses:
                    skipped_units.append(
                        f'{target.get("label", unit_id)} / {weapon} '
                        f'({", ".join(unsafe_weapon_houses)})'
                    )
                    continue
                weapon_values = {}
                for buff_type in ('damage', 'range', 'reload'):
                    if buff_type in weapon_buff_types:
                        applied = (
                            apply_weapon_buff_value(
                                weapon_values,
                                base_stats,
                                buff_type,
                                counts[buff_type],
                            )
                            or applied
                        )
                if not weapon_values:
                    continue
                rule_sections.setdefault(weapon, {}).update(weapon_values)
        if 'damage' in weapon_buff_types and target.get('special_damage_fields'):
            if unsafe_unit_houses:
                skipped_units.append(
                    f'{target.get("label", unit_id)} / spawned missile damage '
                    f'({", ".join(unsafe_unit_houses)})'
                )
            else:
                multiplier = min(2.0, 1.15 ** counts['damage'])
                general_values = rule_sections.setdefault('General', {})
                for field, base_damage in target['special_damage_fields'].items():
                    general_values[field] = str(
                        max(base_damage + 1, int(round(base_damage * multiplier)))
                    )
                applied = True
        if applied:
            applied_units.append(target.get('label', unit_id))

    return (rule_sections, unique_in_order(applied_units), unique_in_order(skipped_units))


def controlled_tech_ids():
    tech_ids = set(EXTRA_TECH_LOCKS)
    for reward in REWARD_POOL:
        tech_ids.update(techlevel_rules_for_reward(reward))
    return tech_ids - {tech_id.upper() for tech_id in ALWAYS_AVAILABLE_TECH_IDS}


def action_line_ids(lines, predicate):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return []

    ids = []
    for line in lines[start + 1:end]:
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        count, groups = parse_action_groups(value)
        if count and predicate(groups):
            ids.append(key.strip())
    return ids


def trigger_action_ids_by_name(lines, patterns):
    start, end = find_section_bounds(lines, 'Triggers')
    if start is None:
        return []

    lowered_patterns = [pattern.lower() for pattern in patterns]
    action_start, _ = find_section_bounds(lines, 'Actions')
    if action_start is None:
        return []
    action_ids = {
        line.split('=', 1)[0].strip().lower()
        for line in section_lines(lines, 'Actions')
        if '=' in line
    }

    ids = []
    for line in lines[start + 1:end]:
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        if key.lower() not in action_ids:
            continue
        value_lower = value.lower()
        if any(pattern in value_lower for pattern in lowered_patterns):
            ids.append(key)
    return ids


def unique_in_order(items):
    seen = set()
    result = []
    for item in items:
        key = item.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def player_country_from_map(lines):
    records = map_house_records(lines)
    house = player_house_from_map(lines, records=records)
    if house:
        return records.get(house, {}).get('country') or house.replace(' House', '')
    return 'UnitedStates'


def player_house_from_map(lines, records=None):
    records = records if records is not None else map_house_records(lines)
    for name, record in records.items():
        if record.get('player'):
            return name
    return ''


def player_controlled_houses(lines, records=None):
    records = records if records is not None else map_house_records(lines)
    return [name for name, record in records.items() if record.get('player')]


def player_transfer_houses(lines, records=None, scripted_enemies=None):
    """Return houses whose complete forces join any player-controlled house."""
    records = records if records is not None else map_house_records(lines)
    player_houses = player_controlled_houses(lines, records=records)
    if not player_houses:
        return []

    player_indexes = set()
    wanted_players = {house.lower() for house in player_houses}
    for line in section_lines(lines, 'Houses'):
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        if value.strip().lower() in wanted_players:
            player_indexes.add(key.strip())
    if not player_indexes:
        return []

    transfer_actions = set()
    for line in section_lines(lines, 'Actions'):
        if '=' not in line:
            continue
        action_id, value = line.split('=', 1)
        _, groups = parse_action_groups(value)
        if any(group[0] == '36' and group[2] in player_indexes for group in groups):
            transfer_actions.add(action_id.strip().lower())

    houses = []
    for line in section_lines(lines, 'Triggers'):
        if '=' not in line:
            continue
        trigger_id, value = line.split('=', 1)
        if trigger_id.strip().lower() not in transfer_actions:
            continue
        parts = [part.strip() for part in value.split(',')]
        if len(parts) < 3 or 'debug' in parts[2].lower():
            continue
        owner = parts[0]
        if owner and owner.lower() not in {'<none>', 'neutral'}:
            houses.append(owner)
    canonical_houses = []
    for house in unique_in_order(houses):
        canonical = canonical_house_name(records, house) or house
        canonical_houses.append(canonical)
    canonical_houses = unique_in_order(canonical_houses)

    # A complete-force transfer can occur after a house has fought the player.
    # Map-local buffs exist from scenario load and cannot be switched off before
    # that transfer, so a house with a scripted hostile phase is not a safe buff
    # target. Start-of-map choice/ownership transfers without such hostility
    # (for example Foehn 04) remain eligible.
    coalition_names = list(player_houses)
    for player in player_houses:
        coalition_names.extend(records.get(player, {}).get('allies', []))
    coalition = set()
    for house in coalition_names:
        canonical = canonical_house_name(records, house)
        if canonical:
            coalition.add(canonical.lower())
    scripted_enemies = (
        scripted_enemy_house_pairs(lines, records=records)
        if scripted_enemies is None
        else scripted_enemies
    )
    return [
        house
        for house in canonical_houses
        if not any(
            frozenset((house.lower(), coalition_house)) in scripted_enemies
            for coalition_house in coalition
            if coalition_house != house.lower()
        )
    ]


def clone_player_country_for_house_buffs(
    lines,
    rewards,
    require_unlocked_access=True,
    additional_unlocked_tech_ids=None,
    share_basic_equivalent_buffs=False,
    unit_specific_mode=False,
):
    player_house = player_house_from_map(lines)
    if not player_house:
        return ('', {})

    house_values = section_value_map(lines, player_house)
    original_country = house_values.get('country') or player_house.replace(' House', '')
    original_values = section_value_map_preserve(lines, original_country)
    house_buff_values = stacked_house_buff_values(
        rewards,
        original_values,
        require_unlocked_access=require_unlocked_access,
        additional_unlocked_tech_ids=additional_unlocked_tech_ids,
        share_basic_equivalent_buffs=share_basic_equivalent_buffs,
        unit_specific_mode=unit_specific_mode,
    )
    if not house_buff_values:
        return (player_house, {})

    # Campaign triggers are owned by the house's Country ID. Never replace it
    # with a private clone: doing so silently detaches the original triggers.
    unsafe_houses = unsafe_country_houses(lines, original_country, [player_house])
    if unsafe_houses:
        return (player_house, {})
    merge_ini_section_values(lines, {original_country: house_buff_values})
    return (player_house, house_buff_values)


def country_inherits_from(lines, country, ancestor, sections=None):
    wanted = (ancestor or '').strip().lower()
    current = (country or '').strip()
    visited = set()
    sections = sections if sections is not None else all_section_value_maps(lines)
    by_lower = {name.lower(): values for name, values in sections.items()}
    while current and current.lower() not in visited:
        current_lower = current.lower()
        if current_lower == wanted:
            return True
        visited.add(current_lower)
        values = by_lower.get(current_lower, {})
        parent = values.get('parentcountry', '').strip()
        if not parent or parent.lower() == current_lower:
            break
        current = parent
    return False


def map_house_records(lines, sections=None):
    """Return map house metadata after a single INI parse.

    Campaign maps can contain hundreds of sections. The former implementation
    rescanned the complete file for the house and country section of every
    listed house, making ownership checks disproportionately expensive during
    launch. A case-insensitive section index preserves the same result in one
    pass.
    """
    sections = sections if sections is not None else all_section_value_maps(lines)
    by_lower = {name.lower(): values for name, values in sections.items()}
    houses = by_lower.get('houses', {})
    records = {}
    for name in houses.values():
        name = name.strip()
        if not name:
            continue
        values = by_lower.get(name.lower(), {})
        country = values.get('country') or name.replace(' House', '')
        country_values = by_lower.get(country.lower(), {})
        records[name] = {
            'name': name,
            'country': country,
            'parent_country': country_values.get('parentcountry', ''),
            'side': country_values.get('side', ''),
            'allies': comma_items(values.get('allies', '')),
            'player': values.get('playercontrol', '').lower() == 'yes',
        }
    return records


def canonical_house_name(records, value):
    """Resolve FinalAlert's House/Country aliases without guessing.

    Trigger owners usually omit the `` House`` suffix. Country names are only
    used as a fallback when exactly one map house uses that country; choosing
    the first shared-country match can silently assign a scripted action to the
    wrong owner.
    """
    wanted = str(value or '').strip().lower()
    if not wanted or wanted in {'<none>', 'none', 'neutral'}:
        return ''

    for name in records:
        if wanted in {name.lower(), name.removesuffix(' House').lower()}:
            return name

    country_matches = [
        name
        for name, record in records.items()
        if wanted == (record.get('country') or '').strip().lower()
    ]
    return country_matches[0] if len(country_matches) == 1 else ''


def scripted_enemy_house_pairs(lines, records=None):
    """Return house pairs that a campaign trigger can make hostile.

    Campaign maps often start future enemies as one-way allies so their units
    remain passive until a story trigger fires. Action 38 (Make Enemy) is the
    reliable distinction between those staged houses and permanent helpers.
    Static rules buffs cannot be removed when that trigger fires, so any such
    house must never be treated as a buffable allied helper.
    """
    records = records if records is not None else map_house_records(lines)
    house_by_index = {}
    for line in section_lines(lines, 'Houses'):
        if '=' not in line:
            continue
        index, value = line.split('=', 1)
        house = canonical_house_name(records, value)
        if house:
            house_by_index[index.strip()] = house

    enemy_targets_by_action = {}
    for line in section_lines(lines, 'Actions'):
        if '=' not in line:
            continue
        action_id, value = line.split('=', 1)
        _, groups = parse_action_groups(value)
        targets = {
            house_by_index.get(group[2].strip(), '')
            for group in groups
            if len(group) >= 3 and group[0] == '38'
        } - {''}
        if targets:
            enemy_targets_by_action[action_id.strip().lower()] = targets

    pairs = set()
    for line in section_lines(lines, 'Triggers'):
        if '=' not in line:
            continue
        trigger_id, value = line.split('=', 1)
        targets = enemy_targets_by_action.get(trigger_id.strip().lower())
        if not targets:
            continue
        tokens = [token.strip() for token in value.split(',')]
        # Debug-only triggers are launcher/map-author utilities, not gameplay.
        if len(tokens) >= 3 and 'debug' in tokens[2].lower():
            continue
        owner = canonical_house_name(records, tokens[0] if tokens else '')
        if not owner:
            continue
        for target in targets:
            if owner.lower() != target.lower():
                pairs.add(frozenset((owner.lower(), target.lower())))
    return pairs


def is_buffable_helper_house(record):
    name = (record.get('name') or '').lower()
    country = (record.get('country') or '').lower()
    parent = (record.get('parent_country') or '').lower()
    blocked = ('neutral', 'civilian', 'special', 'placeholder', 'cinematic')
    if parent in blocked:
        return False
    return not any(token in name or token in country for token in blocked)


def country_family(record):
    text = ' '.join([
        record.get('name') or '',
        record.get('country') or '',
        record.get('parent_country') or '',
        record.get('side') or '',
    ]).lower()
    country_text = ' '.join([
        record.get('name') or '',
        record.get('country') or '',
        record.get('parent_country') or '',
    ]).lower()

    if 'fourthside' in text:
        return 'foehn'
    if any(token in country_text for token in (
        'foehn', 'coronia', 'haiheadquarters', 'hai_headquarters', 'lastbastion'
    )):
        return 'foehn'
    if (
        any(token in country_text for token in ('guild1', 'guild2', 'guild3'))
        and 'europeans' not in country_text
    ):
        return 'foehn'
    if any(token in country_text for token in (
        'psicorps', 'psi_corps', 'scorpion', 'epsilon', 'yuri', 'headquaters'
    )):
        return 'epsilon'
    if any(token in country_text for token in (
        'ussr', 'soviet', 'russia', 'latin', 'chinese', 'iraq', 'cuba', 'libya'
    )):
        return 'soviets'
    if any(token in country_text for token in (
        'unitedstates', 'europeans', 'euro_alliance', 'pacific', 'guild'
    )):
        return 'allies'
    if 'thirdside' in text:
        return 'epsilon'
    if 'nod' in text:
        return 'soviets'
    if 'gdi' in text:
        return 'allies'
    return ''


def allied_helper_houses(
    lines,
    player_house,
    records=None,
    transfer_houses=None,
    scripted_enemies=None,
):
    records = records if records is not None else map_house_records(lines)
    player_record = records.get(player_house)
    if not player_record:
        return []

    player_houses = player_controlled_houses(lines, records=records) or [player_house]
    player_house_names = {name.lower() for name in player_houses}
    player_allies = set()
    for controlled_house in player_houses:
        for ally in records.get(controlled_house, {}).get('allies', []):
            canonical = canonical_house_name(records, ally)
            if canonical:
                player_allies.add(canonical.lower())
    coalition = set()
    coalition_names = list(player_houses)
    for controlled_house in player_houses:
        coalition_names.extend(records.get(controlled_house, {}).get('allies', []))
    if scripted_enemies is None:
        scripted_enemies = scripted_enemy_house_pairs(lines, records=records)
    if transfer_houses is None:
        transfer_houses = player_transfer_houses(
            lines,
            records=records,
            scripted_enemies=scripted_enemies,
        )
    coalition_names.extend(transfer_houses)
    for coalition_name in coalition_names:
        canonical = canonical_house_name(records, coalition_name)
        if canonical:
            coalition.add(canonical.lower())
    helpers = []
    for name, record in records.items():
        if name.lower() in player_house_names or record.get('player'):
            continue
        record_allies = set()
        for ally in record.get('allies', []):
            canonical = canonical_house_name(records, ally)
            if canonical:
                record_allies.add(canonical.lower())
        if name.lower() not in player_allies and not player_house_names.intersection(record_allies):
            continue
        if not is_buffable_helper_house(record):
            continue
        if any(
            frozenset((name.lower(), coalition_house)) in scripted_enemies
            for coalition_house in coalition
            if coalition_house != name.lower()
        ):
            continue
        helpers.append(name)
    return unique_in_order(helpers)


def unsafe_country_houses(
    lines,
    country,
    allowed_house_names,
    records=None,
    sections=None,
    usage_index=None,
    scripted_enemies=None,
):
    allowed = {name.lower() for name in allowed_house_names}
    sections = sections if sections is not None else all_section_value_maps(lines)
    records = records if records is not None else map_house_records(lines, sections=sections)
    usage_index = build_unit_usage_index(lines) if usage_index is None else usage_index
    scripted_enemies = (
        scripted_enemy_house_pairs(lines, records=records)
        if scripted_enemies is None
        else scripted_enemies
    )
    used_houses = set()
    for owners in usage_index.values():
        for owner in owners:
            canonical = canonical_house_name(records, owner)
            used_houses.add((canonical or owner).lower())

    unsafe = []
    for name, record in records.items():
        if not country_inherits_from(
            lines,
            record.get('country'),
            country,
            sections=sections,
        ):
            continue
        name_lower = name.lower()
        if name_lower in allowed:
            continue

        # Empty cinematic/neutral placeholder houses commonly inherit the
        # player's country solely for map scripting. They cannot receive a
        # gameplay buff when they own no placed/scripted TechnoTypes, are
        # allied to the assisted coalition, and never become its enemy. Do not
        # let such a harmless descendant disable every player country bonus.
        record_allies = {
            canonical_house_name(records, ally).lower()
            for ally in record.get('allies', [])
            if canonical_house_name(records, ally)
        }
        allied_to_allowed = bool(record_allies.intersection(allowed)) or any(
            name_lower in {
                canonical_house_name(records, ally).lower()
                for ally in records.get(allowed_house, {}).get('allies', [])
                if canonical_house_name(records, ally)
            }
            for allowed_house in allowed_house_names
        )
        hostile_to_allowed = any(
            frozenset((name_lower, allowed_house)) in scripted_enemies
            for allowed_house in allowed
            if allowed_house != name_lower
        )
        harmless_placeholder = (
            not is_buffable_helper_house(record)
            and name_lower not in used_houses
            and allied_to_allowed
            and not hostile_to_allowed
        )
        if not harmless_placeholder:
            unsafe.append(name)
    return unsafe


def player_country_buff_rules(
    lines,
    rewards,
    buff_allied_helpers=False,
    require_unlocked_access=True,
    additional_unlocked_tech_ids=None,
    share_basic_equivalent_buffs=False,
    unit_specific_mode=False,
):
    sections = all_section_value_maps(lines)
    sections_by_lower = {name.lower(): values for name, values in sections.items()}
    records = map_house_records(lines, sections=sections)
    player_house = player_house_from_map(lines, records=records)
    if not player_house:
        return ('', '', {}, [], [], [])

    player_houses = player_controlled_houses(lines, records=records) or [player_house]
    house_values = sections_by_lower.get(player_house.lower(), {})
    player_country = house_values.get('country') or player_house.replace(' House', '')
    scripted_enemies = scripted_enemy_house_pairs(lines, records=records)
    transfer_houses = player_transfer_houses(
        lines,
        records=records,
        scripted_enemies=scripted_enemies,
    )
    helper_houses = (
        allied_helper_houses(
            lines,
            player_house,
            records=records,
            transfer_houses=transfer_houses,
            scripted_enemies=scripted_enemies,
        )
        if buff_allied_helpers else []
    )
    allowed_houses = unique_in_order(player_houses + transfer_houses + helper_houses)
    usage_index = build_unit_usage_index(lines)
    shared_houses = unsafe_country_houses(
        lines,
        player_country,
        allowed_houses,
        records=records,
        sections=sections,
        usage_index=usage_index,
        scripted_enemies=scripted_enemies,
    )
    rule_sections = {}
    buffed_allies = []
    skipped_allies = []
    original_values = section_value_map_preserve(lines, player_country)
    house_buff_values = stacked_house_buff_values(
        rewards,
        original_values,
        require_unlocked_access=require_unlocked_access,
        additional_unlocked_tech_ids=additional_unlocked_tech_ids,
        share_basic_equivalent_buffs=share_basic_equivalent_buffs,
        unit_specific_mode=unit_specific_mode,
    )
    if house_buff_values:
        if not shared_houses:
            rule_sections[player_country] = house_buff_values

    # Every player-controlled house participates automatically, even when it
    # belongs to another faction. The UI option only adds AI-controlled allied
    # helpers to this mandatory player-house set.
    allied_targets = unique_in_order(
        [house for house in player_houses if house.lower() != player_house.lower()]
        + transfer_houses
        + helper_houses
    )
    if allied_targets:
        for helper in allied_targets:
            helper_country = records.get(helper, {}).get('country') or helper.replace(' House', '')
            if helper_country.lower() == player_country.lower():
                if player_country in rule_sections:
                    buffed_allies.append(helper)
                else:
                    skipped_allies.append(helper)
                continue

            unsafe_houses = unsafe_country_houses(
                lines,
                helper_country,
                allowed_houses,
                records=records,
                sections=sections,
                usage_index=usage_index,
                scripted_enemies=scripted_enemies,
            )
            if unsafe_houses:
                skipped_allies.append(helper)
                continue

            original_values = section_value_map_preserve(lines, helper_country)
            helper_buff_values = stacked_house_buff_values(
                rewards,
                original_values,
                require_unlocked_access=require_unlocked_access,
                additional_unlocked_tech_ids=additional_unlocked_tech_ids,
                share_basic_equivalent_buffs=share_basic_equivalent_buffs,
                unit_specific_mode=unit_specific_mode,
            )
            if helper_buff_values:
                rule_sections[helper_country] = helper_buff_values
                buffed_allies.append(helper)

    return (player_house, player_country, rule_sections, shared_houses, buffed_allies, skipped_allies)


def append_action_to_action_id(lines, action_id, action_tokens):
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return False

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        if key.strip().lower() != action_id.lower():
            continue
        tokens = [token.strip() for token in value.split(',')]
        try:
            tokens[0] = str(int(tokens[0]) + 1)
        except (ValueError, IndexError):
            return False
        tokens.extend(action_tokens)
        replacement = f'{key}={",".join(tokens)}'
        if len(replacement.encode('utf-8')) > MAX_MAP_ACTION_LINE_LENGTH:
            return False
        lines[index] = replacement
        return True
    return False


def insert_actions_before_codes(lines, action_id, action_tokens_list, before_codes):
    """Insert trigger actions before the first matching terminal action.

    Winner/announce-win actions can end the scenario before later actions in
    the same action list run.  Victory markers therefore need to be inserted
    before those actions instead of appended to the list.
    """
    actions = [list(tokens) for tokens in action_tokens_list]
    if not actions or any(len(tokens) != 8 for tokens in actions):
        return False

    wanted_codes = {str(code) for code in before_codes}
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return False

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        if key.strip().lower() != action_id.lower():
            continue

        tokens = [token.strip() for token in value.split(',')]
        try:
            declared_count = int(tokens[0])
        except (ValueError, IndexError):
            return False

        insert_group = None
        for group_index in range(min(declared_count, (len(tokens) - 1) // 8)):
            if tokens[1 + group_index * 8] in wanted_codes:
                insert_group = group_index
                break
        if insert_group is None:
            return False

        insert_at = 1 + insert_group * 8
        inserted_tokens = [token for action in actions for token in action]
        tokens[insert_at:insert_at] = inserted_tokens
        tokens[0] = str(declared_count + len(actions))
        replacement = f'{key}={",".join(tokens)}'
        if len(replacement.encode('utf-8')) > MAX_MAP_ACTION_LINE_LENGTH:
            return False
        lines[index] = replacement
        return True
    return False


def append_parallel_global_hook(lines, source_action_id, marker_action, marker_name):
    """Mirror a global objective trigger when its native action line is full.

    Action lines are capped at 511 bytes, but some campaign objective lists
    already sit near that limit. Global-variable and all-of-type-destroyed
    events can be observed by a second trigger. Mirror native enable/disable
    actions so a source trigger that starts disabled retains its timing.
    """
    events = section_value_map_preserve(lines, 'Events')
    triggers = section_value_map_preserve(lines, 'Triggers')
    source_event = events.get(source_action_id)
    source_trigger = triggers.get(source_action_id)
    if not source_event or not source_trigger or len(marker_action) != 8:
        return False

    event_tokens = [token.strip() for token in source_event.split(',')]
    if len(event_tokens) < 2 or event_tokens[0] != '1' or event_tokens[1] not in {'11', '61'}:
        return False

    trigger_tokens = [token.strip() for token in source_trigger.split(',')]
    if len(trigger_tokens) != 8:
        return False

    hook_trigger_id = unique_section_key(lines, ('Events', 'Actions', 'Triggers'), 'RNH00')
    hook_tag_id = unique_section_key(lines, ('Tags',), 'RHT00')
    source_lower = source_action_id.lower()
    mirrored_lines = []
    mirrored_enable = False
    start, end = find_section_bounds(lines, 'Actions')
    if start is None:
        return False

    for index in range(start + 1, end):
        line = lines[index]
        if '=' not in line:
            continue
        key, value = line.split('=', 1)
        declared_count, groups = parse_action_groups(value)
        if declared_count != len(groups):
            continue

        expanded = []
        changed = False
        for group in groups:
            expanded.append(group)
            if group[0] not in {'53', '54'} or group[2].lower() != source_lower:
                continue
            mirrored = list(group)
            mirrored[2] = hook_trigger_id
            expanded.append(mirrored)
            changed = True
            if group[0] == '53':
                mirrored_enable = True
        if not changed:
            continue

        replacement = f'{key}={len(expanded)},{",".join(action_group_tokens(expanded))}'
        if len(replacement.encode('utf-8')) > MAX_MAP_ACTION_LINE_LENGTH:
            return False
        mirrored_lines.append((index, replacement))

    source_starts_disabled = trigger_tokens[3] == '1'
    if source_starts_disabled and not mirrored_enable:
        return False

    for index, replacement in mirrored_lines:
        lines[index] = replacement

    trigger_tokens[2] = marker_name
    append_section_entry(lines, 'Events', hook_trigger_id, source_event)
    append_section_entry(lines, 'Actions', hook_trigger_id, f'1,{",".join(marker_action)}')
    append_section_entry(lines, 'Triggers', hook_trigger_id, ','.join(trigger_tokens))
    append_section_entry(lines, 'Tags', hook_tag_id, f'0,{marker_name} 1,{hook_trigger_id}')
    return True


def unique_section_key(lines, sections, prefix):
    existing = set()
    for section in sections:
        for line in section_lines(lines, section):
            if '=' in line:
                existing.add(line.split('=', 1)[0].strip().lower())
    for index in range(1, 1000):
        candidate = f'{prefix}{index:03d}'
        if candidate.lower() not in existing:
            return candidate
    raise RuntimeError(f'Could not allocate a unique {prefix} map key.')


SUPERWEAPON_ACTIONS_PER_TRIGGER = 16


def append_superweapon_grant_trigger(lines, house, action_groups):
    """Grant earned powers without overflowing a campaign action list.

    Mental Omega's installed campaign maps top out at 24 actions in one list.
    Large Chaos inventories previously wrote every power into a single list
    (35 in the reported crash), which corrupts the engine while processing the
    map-start trigger. Keep a conservative margin and stagger additional
    chunks by one second so every power is still granted exactly once.
    """
    actions = [list(group) for group in action_groups]
    if not actions or any(len(group) != 8 for group in actions):
        return ''

    trigger_ids = []
    for offset in range(0, len(actions), SUPERWEAPON_ACTIONS_PER_TRIGGER):
        chunk = actions[offset:offset + SUPERWEAPON_ACTIONS_PER_TRIGGER]
        chunk_number = len(trigger_ids) + 1
        trigger_id = unique_section_key(lines, ('Events', 'Actions', 'Triggers'), 'RNGSW')
        tag_id = unique_section_key(lines, ('Tags',), 'RNGST')
        action_tokens = ','.join(action_group_tokens(chunk))
        name = f'MOR Earned Superweapons {chunk_number}'
        append_section_entry(lines, 'Events', trigger_id, f'1,13,0,{chunk_number}')
        append_section_entry(lines, 'Actions', trigger_id, f'{len(chunk)},{action_tokens}')
        append_section_entry(lines, 'Triggers', trigger_id, f'{house},<none>,{name},0,1,1,1,0')
        append_section_entry(lines, 'Tags', tag_id, f'0,{name} 1,{trigger_id}')
        trigger_ids.append(trigger_id)
    return trigger_ids[0]


def append_hook_team(lines, team_id, taskforce_id, script_id, marker_name, house):
    append_section_list_entry(lines, 'TaskForces', taskforce_id)
    append_section_list_entry(lines, 'ScriptTypes', script_id)
    append_section_list_entry(lines, 'TeamTypes', team_id)

    lines.extend([
        '',
        f'[{taskforce_id}]',
        f'Name={marker_name} Empty',
        'Group=-1',
        '',
        f'[{script_id}]',
        '0=11,5',
        f'Name={marker_name} Guard',
        '',
        f'[{team_id}]',
        'Max=1',
        'Full=no',
        f'Name={marker_name}',
        'Group=-1',
        f'House={house}',
        f'Script={script_id}',
        'Whiner=no',
        'Droppod=no',
        'Suicide=no',
        'Loadable=no',
        'Prebuild=no',
        'Priority=1',
        'Waypoint=A',
        'Annoyance=no',
        'IonImmune=no',
        'Recruiter=yes',
        'Reinforce=no',
        f'TaskForce={taskforce_id}',
        'TechLevel=0',
        'Aggressive=no',
        'Autocreate=no',
        'GuardSlower=no',
        'OnTransOnly=no',
        'AvoidThreats=no',
        'LooseRecruit=no',
        'VeteranLevel=1',
        'IsBaseDefense=no',
        'UseTransportOrigin=no',
        'MindControlDecision=0',
        'OnlyTargetHouseEnemy=no',
        'TransportsReturnOnUnload=no',
        'AreTeamMembersRecruitable=no',
    ])


def hook_marker_name(mission_code, check_id):
    if check_id == 'victory':
        suffix = 'VIC'
    else:
        suffix = sanitize_marker_part(check_id.replace('objective_', 'O'), 5)
    return f'MOR_{sanitize_marker_part(mission_code, 10)}_{suffix}'
